# Cross validation In Regression

In [72]:
#import libs
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

#scikit libs
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.model_selection import train_test_split, KFold, cross_val_score

#Regression metrics
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, root_mean_squared_error

In [45]:
#load data
data = pd.read_csv("Advertising.csv")

#drop unamed column
del data["Unnamed: 0"]

#check top 5 rows
data.head()

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [46]:
#check for null values
data.isna().sum().any()

np.False_

In [47]:
#check shape
data.shape

(200, 4)

In [48]:
#seperate label/target from features

#Features
X = data.drop("sales", axis=1)

#label
y = data["sales"]

In [49]:
#split dataset into train and test set

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=41) #for reproducity

#confirm the shape
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((160, 3), (40, 3), (160,), (40,))

In [50]:
x_train[:4]

        TV  radio  newspaper
55   198.9   49.4       60.0
185  205.0   45.1       19.6
106   25.0   11.0       29.7
83    68.4   44.5       35.6

In [51]:
#scale the features

#instantiate the std scaler
sc = StandardScaler()

#scale the xtrain
x_train_s = sc.fit_transform(x_train)

#tranform the x_test
x_test_s = sc.transform(x_test)

x_train_s[:4]

array([[ 0.59877394,  1.69981943,  1.30543051],
       [ 0.67113422,  1.41309888, -0.54779744],
       [-1.46408729, -0.86066174, -0.08449045],
       [-0.94926165,  1.37309137,  0.18615423]])

In [52]:
# instatiate the model and train it

model = LinearRegression()

#train the model
model.fit(x_train_s,y_train)

LinearRegression()

In [53]:
#check training score
round(model.score(x_train_s,y_train),2)

0.9

In [54]:
#model prediction
y_pred = model.predict(x_test_s)

#check actual vs predicted
pd.DataFrame({"actual": y_test, "predicted": y_pred})[:5]

     actual  predicted
96     11.7  12.549102
63     14.0  13.271623
168    17.1  17.097153
196     9.7   8.052953
68     18.9  19.053569

In [56]:
#check model metricts
r2_score(y_pred, y_test)

0.8803925164509865

In [59]:
#MAE

mean_absolute_error(y_test, y_pred)

1.2308992088914157

## crosss validation on Linear Regression

In [60]:
#load data
data = pd.read_csv("Advertising.csv")

#drop unamed column
del data["Unnamed: 0"]

#check top 5 rows
data.head()

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [75]:
#seperate label/target from features

#Features
X = data.drop("sales", axis=1)

sc= StandardScaler()
X_s = sc.fit_transform(X)

#label
y = data["sales"]

In [64]:
#create a model
model2 =LinearRegression()

In [71]:
#createing fold using kfold cv

kf = KFold(n_splits=5)

In [86]:
#fit the model using cv with negative mse as metric or r2 metric
neg_mse_score = cross_val_score(model2, X_s, y, cv=kf, scoring='neg_mean_squared_error' )# or you cam use scoring of "r2'
neg_mse_score

array([-3.1365399 , -2.42566776, -1.58522508, -5.42615506, -2.79114519])

In [87]:
#MSE
mse = -neg_mse_score
mse

array([3.1365399 , 2.42566776, 1.58522508, 5.42615506, 2.79114519])

In [88]:
#get one result(average mse)

np.mean(mse)

np.float64(3.07294659710021)

In [89]:
#fit the model using cv with r2 metric
r2_score = cross_val_score(model2, X_s, y, cv=kf, scoring='r2' )# or you cam use scoring of "r2'
r2_score

array([0.87865198, 0.91763212, 0.92933032, 0.81443904, 0.89547829])

In [90]:
#get average r2 score
np.mean(r2_score)

np.float64(0.8871063495438435)

### assignment  1

Create Decision Tree base model using train_test split approach, and rectreate the model using kfold cross validation

In [91]:
#get the regression model 
from sklearn.tree import DecisionTreeRegressor

## assignment 2

Create randomforest model using train_test split approach, and rectreate the model using kfold cross validation

In [97]:
# clssification model approach 
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, auc, balanced_accuracy_score, roc_curve
from sklearn.ensemble import RandomForestClassifier

In [93]:
#load the dataset

df = pd.read_csv("diabetes.csv")
df[:5]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1